class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Moto Q11 Sync Recovery',
      'app_title': 'Moto Q11 Sync Recovery',
      'app_subtitle': 'OpenWrt Unlock & Local Mesh Manager',
      'tab_setup': 'Setup & Patch',
      'tab_network': 'Mesh Network',
      'tab_guides': 'Hardware Guides',
      'nav_setup': 'Setup Wizard',
      'nav_topology': 'Mesh Topology',
      'nav_guides': 'Hardware Guides',
      'language': 'Language',
      'lang_english': 'English',
      'lang_spanish': 'Español (México)',
      'kit_config_title': 'Motorola Q11 Kit Selection',
      'node_single': '1 Node (MH7601)',
      'node_two': '2 Nodes (MH7602)',
      'node_three': '3 Nodes (MH7603 Mesh)',
      'step_process_title': 'Step-by-Step Recovery Process',
      'factory_reset_alert_title': 'Recommended: Factory Reset Router',
      'factory_reset_alert_desc':
          'If this router was previously used or configured, custom passwords or custom IP subnets (e.g. 10.10.11.x) will prevent unlocking. Press and hold the rear pinhole Reset button for 10–15 seconds until the front LED flashes Amber to restore default label credentials and 192.168.1.1 IP.',
      'guide_reset_title': 'Factory Reset Pinhole Guide',
      'guide_reset_desc':
          'Insert a paperclip into the rear RESET pinhole while powered on. Hold for 10–15s until the LED turns Amber. Wait 2 minutes for full reboot.',
      'step_1_title': 'Step 1: Select Mesh Kit Size',
      'step_1_desc':
          'Choose whether you are setting up 1 standalone router (MH7601) or a multi-node mesh system (2 or 3 Nodes).',
      'btn_next_wifi': 'Confirm Kit & Define WiFi',
      'step_2_title': 'Step 2: Define Mesh WiFi Networks',
      'step_2_desc':
          'Set the WiFi network names (SSID) and passwords to be applied and broadcast across all mesh nodes.',
      'btn_save_and_flash': 'Save WiFi & Proceed to Flashing',
      'step_3_title': 'Step 3: Flash & Configure Nodes',
      'step_3_desc':
          'Unlock and apply the OpenWrt patch with your pre-configured WiFi to the Master node, then flash each Satellite node.',
      'node_master_flash_title': 'Master Node (Gateway)',
      'node_satellite_flash_title': 'Satellite Node {0}',
      'btn_flash_master': 'Flash Master Node',
      'btn_flash_satellite': 'Flash Satellite Node {0}',
      'btn_next_placement': 'All Nodes Flashed! Proceed to Placement',
      'label_default_ssid': 'Default WiFi SSID (Label)',
      'label_wifi_password': 'WiFi Password (Label)',
      'label_router_ip': 'Router IP Address',
      'status_ready': 'Ready to begin...',
      'btn_scan_qr': 'Scan QR Code',
      'step_4_title': 'Step 4: Connect Master WAN & Place Satellites',
      'step_4_desc':
          'Connect the Master router to your internet modem and place satellites in your home.',
      'step_4_master_instruction':
          '1. Connect Ethernet cable from your ISP Modem/ONT into the Master WAN port (Globe 🌐).',
      'step_4_satellite_instruction':
          '2. Place satellite nodes within Wi-Fi range (1–2 rooms away). Plug in USB-C power.',
      'step_4_led_instruction':
          '3. Wait ~2 minutes. Confirm all node front LEDs turn Solid White.',
      'btn_confirm_placement': 'Confirm Placement & Run Tests',
      'step_5_title': 'Step 5: Automated Verification & Health Suite',
      'step_5_desc':
          'Run automated diagnostics to verify Internet uplink, router services, and mesh node connectivity.',
      'btn_run_tests': 'Run Verification Tests',
      'test_status_running': 'Running diagnostics suite...',
      'test_status_passed': '✅ All tests passed! Network is fully operational.',
      'test_status_warning': '⚠️ Some checks reported warnings. See details below.',
      'test_check_internet': 'Internet Uplink (WAN & DNS)',
      'test_check_services': 'Router Services (Ports 22, 80, 8080, 7681)',
      'test_check_mesh': 'Mesh Satellites Reachability',
      'test_check_clients': 'Active DHCP Clients',
      'btn_goto_topology': 'View Mesh Topology',
      'home_network_title': 'Home Network (2.4 GHz & 5 GHz)',
      'guest_network_title': 'Guest Network (2.4 GHz & 5 GHz)',
      'label_ssid': 'Network Name (SSID)',
      'label_password': 'Password',
      'btn_save_wifi': 'Save & Apply Mesh WiFi',
      'network_overview': 'Mesh Network Overview',
      'network_desc':
          'Visual view of your local mesh nodes, connection status, and active devices.',
      'role_master': 'Master Node (Gateway)',
      'role_satellite': 'Mesh Satellite Node',
      'status_online': 'Online',
      'status_offline': 'Offline / Unreachable',
      'status_patched': 'Patched (OpenWrt)',
      'status_unpatched': 'Stock / Unpatched',
      'backhaul_wifi': '5 GHz Wireless Mesh',
      'backhaul_ethernet': 'Ethernet Backhaul',
      'btn_add_satellite': 'Add Satellite Node',
      'btn_refresh_network': 'Refresh Network Status',
      'btn_open_admin': 'Open Web Admin',
      'btn_open_terminal': 'Open Web Terminal (ttyd)',
      'btn_delete_node': 'Remove Node',
      'active_devices_title': 'Active Connected Devices (DHCP Leases)',
      'no_devices_found': 'No connected client devices discovered yet.',
      'no_satellites_added':
          "No satellite nodes registered. Tap 'Add Satellite Node' or scan its QR label.",
      'scanner_title': 'Scan Motorola Q11 QR Code',
      'scanner_instruction': 'Align the QR code from the bottom label inside the frame',
      'scanner_desktop_fallback': 'Manual Credential Input / Payload',
      'btn_apply_payload': 'Apply Extracted Credentials',
      'camera_permission_title': 'Camera Permission Needed',
      'camera_permission_msg':
          'Camera access is required to scan the router label QR code.',
      'btn_grant_permission': 'Grant Permission',
      'btn_cancel': 'Cancel',
      'qr_scanned_toast': 'Router credentials detected and applied!',
      'guide_ports_title': 'Rear Ports Guide',
      'port_wan_title': 'WAN (Globe 🌐)',
      'port_wan_desc': 'Ethernet cable to ISP modem (Master only)',
      'port_usbc_title': 'USB-C Power',
      'port_usbc_desc': 'Original 5V DC 3A power adapter',
      'port_lan_title': 'LAN (<···>)',
      'port_lan_desc': 'For PC, switch, or wired backhaul',
      'guide_led_title': 'Front LED Status Indicator',
      'led_amber_title': 'Amber',
      'led_amber_desc': 'Booting or No WAN connection to modem',
      'led_blue_title': 'Blue',
      'led_blue_desc': 'Syncing or Mesh pairing in progress',
      'led_white_title': 'White',
      'led_white_desc': 'Optimal / Online and operating normally',
      'local_storage_badge': '100% On-Device Local Storage',
      'config_backup_title': 'Network Configuration Backup',
      'btn_export_config': 'Export Config (JSON)',
      'btn_import_config': 'Import Config (JSON)',
      'export_dialog_title': 'Export Network Configuration',
      'export_dialog_desc':
          'Copy this JSON configuration or save it to apply to another network or replacement device.',
      'import_dialog_title': 'Import Network Configuration',
      'import_dialog_desc':
          'Paste or select a previously exported network JSON configuration file:',
      'btn_copy_json': 'Copy to Clipboard',
      'btn_share_json': 'Share JSON File',
      'btn_apply_import': 'Apply Configuration',
      'export_success_toast': 'Configuration exported and copied to clipboard!',
      'import_success_toast': 'Network configuration imported successfully!',
      'import_error_toast': 'Failed to import configuration: Invalid JSON format.',
      'about_author_title': 'App Author & Developer',
      'author_name': 'Carlos Armenta (@carlosarmentac)',
      'author_bio': 'IoT, Python, NodeJS, and @vuejs fan.',
      'author_github_label': 'GitHub: carlosarmentac',
      'author_email_label': 'Email: carlos.armentac@gmail.com',
      'credits_title': 'Credits & References',
      'credit_jabeg_label': 'Motorola Q11 OpenWrt (jabeg)',
      'credit_energy_label': 'SSH Enable Method (energy-x)',
      'credit_broadcom_label': 'Broadcom BCM6756 Datasheet',
      'credit_openwrt_label': 'OpenWrt Wiki & Documentation',
      'diag_title': 'Subnet Scanner & Diagnostics',
      'btn_scan_subnet': 'Scan Subnet (.1 to .254)',
      'btn_ping': 'Ping Target',
      'btn_tracepath': 'Tracepath Route',
      'diag_target_ip_label': 'Target IP Address',
      'unconfigured_network_title': 'No Mesh Topology Configured',
      'unconfigured_network_desc':
          'Scan your active physical LAN network to automatically discover your Motorola Q11 Master Router and Satellite nodes.',
      'btn_autodetect_scan': 'Auto-Detect & Scan Network',
      'btn_rescan_network': 'Re-Scan Entire Network',
      'discovered_nodes_title': 'Discovered Motorola Q11 Devices',
      'btn_add_to_topology': 'Add Selected to Topology',
      'btn_set_as_master': 'Set as Master Gateway',
      'btn_add_as_satellite': 'Add as Satellite Node',
      'device_added_toast': 'Device added to Mesh Topology!',
      'btn_identify_led': 'Flash LED (15s)',
      'flashing_led_toast': 'Flashing LED on {0} for 15 seconds...',
      'btn_device_stats': 'Device Stats',
      'device_stats_title': 'Device Diagnostics & Telemetry',
      'cpu_load_label': 'CPU Load',
      'memory_usage_label': 'Memory (RAM)',
      'uptime_label': 'System Uptime',
      'active_ssids_label': 'Active Broadcast SSIDs',
      'no_ssids_found': 'No active SSIDs queried.',
      'btn_backup_device': 'Backup Config',
      'btn_restore_device': 'Restore Config',
      'device_backup_success': 'Device configuration backup downloaded successfully!',
      'device_restore_success': 'Configuration restored to {0}! Network restarting.',
      'device_restore_failed': 'Failed to restore configuration to device.',
      'speedtest_title': 'Network Speed Test',
      'btn_start_speedtest': 'Start Speed Test',
      'speedtest_latency': 'Latency',
      'speedtest_jitter': 'Jitter',
      'speedtest_download': 'Download',
      'speedtest_upload': 'Upload',
      'connected_device_badge': 'Directly Connected Node (You)',
      'disclaimer_title': 'Disclaimer & Community Notice',
      'disclaimer_text':
          'Use this tool entirely at your own risk. This project is an independent community and open-source effort aimed at rescuing and recycling abandoned devices such as the Motorola Q11. We are not affiliated with, endorsed by, or in any relationship with Motorola or Minim.',
      'license_notice': 'Released as open-source software under the MIT License.',
    },
    'es': {
      'app_name': 'Moto Q11 Sync Recovery',
      'app_title': 'Recuperación Moto Q11',
      'app_subtitle': 'Liberación OpenWrt y Gestor Mesh Local',
      'tab_setup': 'Configuración',
      'tab_network': 'Red Mesh',
      'tab_guides': 'Guías de Hardware',
      'nav_setup': 'Asistente de Configuración',
      'nav_topology': 'Topología Mesh',
      'nav_guides': 'Guías de Hardware',
      'language': 'Idioma',
      'lang_english': 'English',
      'lang_spanish': 'Español (México)',
      'kit_config_title': 'Selección de Kit Motorola Q11',
      'node_single': '1 Nodo (MH7601)',
      'node_two': '2 Nodos (MH7602)',
      'node_three': '3 Nodos (MH7603 Mesh)',
      'step_process_title': 'Proceso de Recuperación Paso a Paso',
      'factory_reset_alert_title': 'Recomendado: Restablecer Router de Fábrica',
      'factory_reset_alert_desc':
          'Si este router fue usado previamente, las contraseñas personalizadas o subredes IP impedirán el desbloqueo. Mantén presionado el botón RESET trasero durante 10–15 segundos hasta que el LED parpadee en color Ámbar.',
      'guide_reset_title': 'Guía del Botón de Reseteo (Reset Pinhole)',
      'guide_reset_desc':
          'Inserta un clip en el orificio RESET con el equipo encendido. Mantén presionado 10–15s hasta que el LED cambie a Ámbar. Espera 2 minutos.',
      'step_1_title': 'Paso 1: Seleccionar Tamaño del Kit Mesh',
      'step_1_desc':
          'Elige si vas a configurar 1 router individual (MH7601) o un sistema mesh multi-nodo (2 o 3 Nodos).',
      'btn_next_wifi': 'Confirmar Kit y Definir WiFi',
      'step_2_title': 'Paso 2: Definir Redes WiFi Mesh',
      'step_2_desc':
          'Define los nombres de red (SSID) y contraseñas que se sincronizarán y transmitirán en todos los nodos.',
      'btn_save_and_flash': 'Guardar WiFi y Proceder a Flashear',
      'step_3_title': 'Paso 3: Flashear y Configurar Nodos',
      'step_3_desc':
          'Desbloquea y aplica el parche OpenWrt con tu WiFi al nodo Maestro, y luego flashea cada Satélite.',
      'node_master_flash_title': 'Nodo Maestro (Puerta de Enlace)',
      'node_satellite_flash_title': 'Nodo Satélite {0}',
      'btn_flash_master': 'Flashear Nodo Maestro',
      'btn_flash_satellite': 'Flashear Nodo Satélite {0}',
      'btn_next_placement': '¡Nodos Flasheados! Proceder a la Ubicación',
      'label_default_ssid': 'SSID WiFi por Defecto (Etiqueta)',
      'label_wifi_password': 'Contraseña WiFi (Etiqueta)',
      'label_router_ip': 'Dirección IP del Router',
      'status_ready': 'Listo para iniciar...',
      'btn_scan_qr': 'Escanear Código QR',
      'step_4_title': 'Paso 4: Conectar WAN del Maestro y Colocar Satélites',
      'step_4_desc':
          'Conecta el router Maestro a tu módem de internet y ubica los satélites en tu hogar.',
      'step_4_master_instruction':
          '1. Conecta el cable Ethernet de tu módem/ONT al puerto WAN (Mundo 🌐) del Maestro.',
      'step_4_satellite_instruction':
          '2. Coloca los satélites dentro del rango Wi-Fi (a 1 o 2 habitaciones). Conecta la energía USB-C.',
      'step_4_led_instruction':
          '3. Espera ~2 minutos. Confirma que el LED frontal de todos los nodos encienda en Blanco Fijo.',
      'btn_confirm_placement': 'Confirmar Ubicación y Ejecutar Pruebas',
      'step_5_title': 'Paso 5: Pruebas Automáticas de Diagnóstico',
      'step_5_desc':
          'Ejecuta diagnósticos automatizados para verificar salida a Internet, servicios y enlace mesh.',
      'btn_run_tests': 'Ejecutar Pruebas de Verificación',
      'test_status_running': 'Ejecutando suite de diagnósticos...',
      'test_status_passed': '✅ ¡Todas las pruebas pasaron! La red está 100% operativa.',
      'test_status_warning': '⚠️ Algunas pruebas reportaron advertencias. Revisa los detalles.',
      'test_check_internet': 'Salida a Internet (WAN y DNS)',
      'test_check_services': 'Servicios del Router (Puertos 22, 80, 8080, 7681)',
      'test_check_mesh': 'Conectividad de Nodos Satélite',
      'test_check_clients': 'Clientes DHCP Conectados',
      'btn_goto_topology': 'Ver Topología Mesh',
      'home_network_title': 'Red Principal (2.4 GHz y 5 GHz)',
      'guest_network_title': 'Red de Visitas / Invitados (2.4 GHz y 5 GHz)',
      'label_ssid': 'Nombre de Red (SSID)',
      'label_password': 'Contraseña',
      'btn_save_wifi': 'Guardar y Aplicar Redes Mesh',
      'network_overview': 'Vista General de la Red Mesh',
      'network_desc':
          'Visualización de tus nodos mesh locales, estado de enlace y dispositivos conectados.',
      'role_master': 'Nodo Maestro (Puerta de Enlace)',
      'role_satellite': 'Nodo Satélite Mesh',
      'status_online': 'En línea',
      'status_offline': 'Desconectado / Inaccesible',
      'status_patched': 'Parcheado (OpenWrt)',
      'status_unpatched': 'Bloqueado de Fábrica',
      'backhaul_wifi': 'Enlace Mesh Inalámbrico 5 GHz',
      'backhaul_ethernet': 'Enlace Ethernet por Cable',
      'btn_add_satellite': 'Agregar Nodo Satélite',
      'btn_refresh_network': 'Actualizar Estado de Red',
      'btn_open_admin': 'Abrir Panel de Control Web',
      'btn_open_terminal': 'Abrir Terminal Web (ttyd)',
      'btn_delete_node': 'Eliminar Nodo',
      'active_devices_title': 'Dispositivos Conectados Activos (Arrendamientos DHCP)',
      'no_devices_found': 'Aún no se detectan dispositivos clientes conectados.',
      'no_satellites_added':
          "No hay satélites registrados. Pulsa 'Agregar Nodo Satélite' o escanea su etiqueta QR.",
      'scanner_title': 'Escanear Código QR Motorola Q11',
      'scanner_instruction': 'Alinea el código QR de la etiqueta inferior dentro del marco',
      'scanner_desktop_fallback': 'Entrada Manual de Credenciales / Payload',
      'btn_apply_payload': 'Aplicar Credenciales Extraídas',
      'camera_permission_title': 'Permiso de Cámara Requerido',
      'camera_permission_msg':
          'Se requiere acceso a la cámara para escanear el código QR del router.',
      'btn_grant_permission': 'Conceder Permiso',
      'btn_cancel': 'Cancelar',
      'qr_scanned_toast': '¡Credenciales del router detectadas y aplicadas!',
      'guide_ports_title': 'Guía de Puertos Posteriores',
      'port_wan_title': 'WAN (Mundo 🌐)',
      'port_wan_desc': 'Cable Ethernet hacia tu módem de internet (Solo Maestro)',
      'port_usbc_title': 'Alimentación USB-C',
      'port_usbc_desc': 'Cargador original de 5V DC 3A',
      'port_lan_title': 'LAN (<···>)',
      'port_lan_desc': 'Para PC, consola o enlace cableado entre satélites',
      'guide_led_title': 'Indicador LED Frontal',
      'led_amber_title': 'Ámbar',
      'led_amber_desc': 'Iniciando o Sin conexión WAN con el módem',
      'led_blue_title': 'Azul',
      'led_blue_desc': 'Sincronizando o Emparejamiento Mesh en curso',
      'led_white_title': 'Blanco',
      'led_white_desc': 'Óptimo / En línea y operando con normalidad',
      'local_storage_badge': 'Almacenamiento 100% Local en el Dispositivo',
      'config_backup_title': 'Respaldo de Configuración de Red',
      'btn_export_config': 'Exportar Config (JSON)',
      'btn_import_config': 'Importar Config (JSON)',
      'export_dialog_title': 'Exportar Configuración de Red',
      'export_dialog_desc':
          'Copia esta configuración JSON o guárdala para aplicarla a otra red o dispositivo de reemplazo.',
      'import_dialog_title': 'Importar Configuración de Red',
      'import_dialog_desc':
          'Pega o selecciona un archivo de configuración JSON exportado previamente:',
      'btn_copy_json': 'Copiar al Portapapeles',
      'btn_share_json': 'Compartir Archivo JSON',
      'btn_apply_import': 'Aplicar Configuración',
      'export_success_toast': '¡Configuración exportada y copiada al portapapeles!',
      'import_success_toast': '¡Configuración de red importada exitosamente!',
      'import_error_toast': 'Error al importar configuración: Formato JSON inválido.',
      'about_author_title': 'Autor y Desarrollador de la App',
      'author_name': 'Carlos Armenta (@carlosarmentac)',
      'author_bio': 'Fan de IoT, Python, NodeJS y @vuejs.',
      'author_github_label': 'GitHub: carlosarmentac',
      'author_email_label': 'Correo: carlos.armentac@gmail.com',
      'credits_title': 'Créditos y Referencias',
      'credit_jabeg_label': 'Motorola Q11 OpenWrt (jabeg)',
      'credit_energy_label': 'Método de Activación SSH (energy-x)',
      'credit_broadcom_label': 'Ficha Técnica Broadcom BCM6756',
      'credit_openwrt_label': 'Wiki y Documentación de OpenWrt',
      'diag_title': 'Escáner de Subred y Diagnósticos',
      'btn_scan_subnet': 'Escanear Subred (.1 a .254)',
      'btn_ping': 'Hacer Ping a IP',
      'btn_tracepath': 'Trazar Ruta (Tracepath)',
      'diag_target_ip_label': 'Dirección IP Objetivo',
      'unconfigured_network_title': 'Sin Topología Mesh Configurada',
      'unconfigured_network_desc':
          'Escanea tu red física local para detectar automáticamente tu Router Maestro Motorola Q11 y los nodos Satélites.',
      'btn_autodetect_scan': 'Autodetectar y Escanear Red',
      'btn_rescan_network': 'Reescanear Toda la Red',
      'discovered_nodes_title': 'Dispositivos Motorola Q11 Detectados',
      'btn_add_to_topology': 'Agregar a la Topología',
      'btn_set_as_master': 'Asignar como Maestro',
      'btn_add_as_satellite': 'Agregar como Satélite',
      'device_added_toast': '¡Dispositivo agregado a la Topología Mesh!',
      'btn_identify_led': 'Parpadear LED (15s)',
      'flashing_led_toast': 'Parpadeando LED en {0} durante 15 segundos...',
      'btn_device_stats': 'Estadísticas del Dispositivo',
      'device_stats_title': 'Diagnósticos y Telemetría del Dispositivo',
      'cpu_load_label': 'Carga de CPU',
      'memory_usage_label': 'Memoria (RAM)',
      'uptime_label': 'Tiempo Activo (Uptime)',
      'active_ssids_label': 'SSIDs Transmitidos Activos',
      'no_ssids_found': 'No se encontraron SSIDs configurados.',
      'btn_backup_device': 'Respaldar Config',
      'btn_restore_device': 'Restaurar Config',
      'device_backup_success': '¡Respaldo de configuración del router descargado con éxito!',
      'device_restore_success': '¡Configuración restaurada en {0}! Reiniciando red.',
      'device_restore_failed': 'Error al restaurar configuración en el router.',
      'speedtest_title': 'Prueba de Velocidad de Red',
      'btn_start_speedtest': 'Iniciar Test de Velocidad',
      'speedtest_latency': 'Latencia',
      'speedtest_jitter': 'Jitter',
      'speedtest_download': 'Descarga',
      'speedtest_upload': 'Subida',
      'connected_device_badge': 'Nodo Directamente Conectado (Tú)',
      'disclaimer_title': 'Descargo de Responsabilidad y Aviso Comunitario',
      'disclaimer_text':
          'Usa esta herramienta bajo tu propio riesgo. Este proyecto es un esfuerzo comunitario independiente y de código abierto para rescatar y reciclar dispositivos abandonados como el Motorola Q11. No pertenecemos ni tenemos relación alguna con Motorola o Minim.',
      'license_notice': 'Publicado como software de código abierto bajo la Licencia MIT.',
    }
  };

  static String tr(String key, String lang, [List<dynamic>? args]) {
    final langMap = _localizedValues[lang] ?? _localizedValues['en']!;
    var text = langMap[key] ?? _localizedValues['en']![key] ?? key;
    if (args != null && args.isNotEmpty) {
      for (var i = 0; i < args.length; i++) {
        text = text.replaceAll('{$i}', args[i].toString());
      }
    }
    return text;
  }
}
